### ISSUE TITLE
Error when running starter-react-flux init

### ISSUE THREAD

**Issue by LawnboyMax** [SokichiFujita/starter-react-flux#19]
## Output after running `starter-react-flux init`

```
> starter-react-flux init
*** starter-react-flux ***
Create: ./app
Create: ./app/actions
Create: ./app/constants
Create: ./app/components
Create: ./app/dispatcher
Create: ./app/stores
Create: ./app/utils
Create: ./public
Create: ./public/css
Create: ./public/img
Create: ./public/js
Create: ./__tests__
Fix: package.json Key: description
Fix: package.json Key: repository
Fix: package.json Key: jest
Fix: package.json Key: scripts
Fix: package.json Key: keywords
Fix: package.json Key: license
Create: .eslintrc
Create: .babelrc
C:\Users\user\AppData\Roaming\npm\node_modules\starter-react-flux\bin
Read: C:\Users\user\AppData\Roaming\npm\node_modules\starter-react-flux\bin\public\index.html
Create: ./public/index.html
Read: C:\Users\user\AppData\Roaming\npm\node_modules\starter-react-flux\bin\public\main.css
Create: ./public/css/style.css
Read: C:\Users\user\AppData\Roaming\npm\node_modules\starter-react-flux\bin\app\webpack.js
Create: webpack.config.js
Read: C:\Users\user\AppData\Roaming\npm\node_modules\starter-react-flux\bin\app\App.js
Create: ./app/App.js
Read: C:\Users\user\AppData\Roaming\npm\node_modules\starter-react-flux\bin\app\dispatcher\dispatcher.js
Create: ./app/dispatcher/AppDispatcher.js
Read: C:\Users\user\AppData\Roaming\npm\node_modules\starter-react-flux\bin\app\constants\constant.js
Create: ./app/constants/AppConstants.js
Read: C:\Users\user\AppData\Roaming\npm\node_modules\starter-react-flux\bin\app\components\Navi.js
Create: ./app/components/Navi.js
Read: C:\Users\user\AppData\Roaming\npm\node_modules\starter-react-flux\bin\app\components\Menu.js
Create: ./app/components/Menu.js
Read: C:\Users\user\AppData\Roaming\npm\node_modules\starter-react-flux\bin\app\components\Content.js
Create: ./app/components/Content.js
Read: C:\Users\user\AppData\Roaming\npm\node_modules\starter-react-flux\bin\__tests__\Content-test.js
Create: ./__tests__/Content-test.js
Create: ./app/stores/SampleStore.js
Create: ./app/actions/SampleActionCreators.js
Create: ./app/components/TopContainer.js
Create: ./app/components/SampleContainer.js
npm install yarn
npm notice created a lockfile as package-lock.json. You should commit this file.
./node_modules/yarn/bin/yarn add --dev babel-cli
'.' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:644
    throw err;
    ^

Error: Command failed: ./node_modules/yarn/bin/yarn add --dev babel-cli
'.' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at npms.map.command (C:\Users\user\AppData\Roaming\npm\node_modules\starter-react-flux\bin\index.js:248:5)
    at Array.map (<anonymous>)
    at npmInstall (C:\Users\user\AppData\Roaming\npm\node_modules\starter-react-flux\bin\index.js:246:8)
    at setupReact (C:\Users\user\AppData\Roaming\npm\node_modules\starter-react-flux\bin\index.js:238:3)
    at main (C:\Users\user\AppData\Roaming\npm\node_modules\starter-react-flux\bin\index.js:155:9)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\starter-react-flux\bin\index.js:147:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
```

## System Info

Windows 10, 64-bit
npm 5.6.0

**Comment by SokichiFujita** [comment]
Thanks. It may be an error on Windows environment.  I’ll fix the error.

**Comment by SokichiFujita** [comment]
@LawnboyMax I've just updated the version to fix the bug on Windows environment. Please try [new installation way](https://github.com/SokichiFujita/starter-react-flux#create-a-new-project).
